In [1]:
import numpy as np 

In [3]:
arr = np.array([1,2,3])

## dimensiions and shape 

In [7]:
arr.ndim

1

In [9]:
arr =np.array(34)
arr.ndim

0

In [21]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [23]:
range = np.arange(1,10, 2) #start, stop, step

In [25]:
range

array([1, 3, 5, 7, 9])

In [27]:
arr = np.linspace(0,1,10) #start, stop, number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
arr = np.logspace(1, 3, 2) #logarithmic scale array -> 10^1 -> 10^3 ... 3 points
arr

array([  10., 1000.])

In [33]:
arr = np.zeros([2,3]) #array full of zeros
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
arr = np.ones([4,3]) #array full of ones
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
arr = np.full(10, 2) #-> create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [41]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [43]:
arr = np.empty([2,3]) #Uninitialized array -> create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
arr = np.random.rand(2,3)
arr

array([[0.56211464, 0.34609571, 0.5524275 ],
       [0.08291735, 0.78899718, 0.21109765]])

In [47]:
arr = np.random.randn(2,3)
arr #-> random floats from standard normal distribution

array([[ 0.12405037,  0.83193696, -0.17275379],
       [-0.75255757, -1.64134926,  0.68388018]])

In [49]:
arr = np.random.randint(10, 100) #->start, stop, dimension/number of values
arr#-> random integers

32

In [51]:
arr = np.random.randint(10, 100, size = (2,3)) #->start, stop, dimension/number of values
arr

array([[44, 36, 75],
       [27, 63, 76]])

# NumPy Data Types $ Type Casting

In [55]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [57]:
type(arr)

numpy.ndarray

In [59]:
print(type(arr))

<class 'numpy.ndarray'>


In [69]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [71]:
print(type(lst))

<class 'list'>


In [73]:
# typecasting -> astype()

In [75]:
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [77]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [79]:
new_arr.dtype

dtype('float64')

In [81]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3], dtype=int64)

In [83]:
 # type casting errors

In [85]:
arr = np.array(["1", "2", "hello"])
arr2 = arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: 'hello'

In [87]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [91]:
arr.ndim

2

In [93]:
arr.shape

(2, 3)

In [95]:
arr.size

6

In [97]:
arr.itemsize

4

# Array Reshaping -> Reshape, Ravel, flatten

In [100]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
reshape2 = reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Arithmetic Operations on Arrays

In [119]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [121]:
(a + b)

array([5, 7, 9])

In [123]:
a-b

array([-3, -3, -3])

In [125]:
print(b//a)

[4 2 2]


In [127]:
print(a*b)

[ 4 10 18]


In [129]:
print(b%a)

[0 1 0]


In [132]:
print(a**2)

[1 4 9]


# Universal Function -> ufuncs

In [134]:
arr = np.array([1,4,9,16])

In [136]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [138]:
# exponentioal -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [140]:
#sine function -> np.sin

angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


# Indexing and Slicing

In [147]:
a = [1,2,3,4,5]
a[-1:-4: -1]

[5, 4, 3]

In [149]:
a[-1:-4: -1]

[5, 4, 3]

In [151]:
a[: :2]

[1, 3, 5]

In [153]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [155]:
# Negative Indexing
print(arr[-1])

50


In [157]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [159]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [161]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [163]:
# Iterating with nditer()

In [165]:
arr= np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [167]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [169]:
# ndenumerate() -> both index + value

for ind, x in np.ndenumerate(arr):
  print(ind, x)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


# Views vs Copies

In [172]:
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [174]:
view[0] = 200

In [176]:
arr

array([  1, 200,   3,   4,   5])

In [178]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [180]:
copy[0] = 2
copy

array([2, 3])

In [182]:
arr

array([  1, 200,   3,   4,   5])

In [184]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [186]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [188]:
arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [190]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)